# Generated by Django 5.2.6 on 2025-09-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='duration',
        ),
        migrations.AddField(
            model_name='story',
            name='duration_hours',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
